### ISSUE TITLE
Outdated MIPS toolchain

### ISSUE THREAD

**Issue by polachok** [rust-lang-nursery/libc#100]
I think we waste too much time on workarounds for its problems. It was built when debian squeezy was all the rage (almost 5 years ago). Let's just drop it and use something more modern.

Linux-mips website has a list of [toolchains](https://www.linux-mips.org/wiki/Toolchains) we can use.
I created a [branch](https://github.com/polachok/libc/pull/1) using [CodeScape MIPS SDK](https://community.imgtec.com/developers/mips/tools/codescape-mips-sdk/download-codescape-mips-sdk-essentials/). It currently [fails](https://travis-ci.org/polachok/libc/jobs/97108825) on linking stage, but I thought it would be a good idea to ask of your opinion before researching it further.

**Comment by alexcrichton** [comment]
Yeah I'd be totally down for using a newer toolchain, I definitely agree the one we're using is quite old! It was basically just the first one that I ran across :)

**Comment by derekdreery** [comment]
This seems to be the easiest way?

https://wiki.debian.org/CrossToolchains

**Comment by polachok** [comment]
See https://github.com/rust-lang-nursery/libc/pull/114
