### ISSUE TITLE
libc should provide libc::c_bool

### ISSUE THREAD

**Issue by jimblandy** [rust-lang-nursery/libc#116]
The libc crate should export a type `c_bool`, defined to have the same representation as the C and C++ `bool` type on the current platform, analogous to `c_int` and so on.

**Comment by steveklabnik** [comment]
:+1:

**Comment by alexcrichton** [comment]
Closing along the lines of https://github.com/rust-lang-nursery/libc/pull/128 which resulted in https://github.com/rust-lang/rfcs/pull/954#issuecomment-169820630 (and discussion can be continued there)
