### ISSUE TITLE
eventfd() unsigned int

### ISSUE THREAD

**Issue by MarkSwanson** [rust-lang-nursery/libc#120]
In Linux note 'man 2 eventfd'.
       int eventfd(unsigned int initval, int flags);

You'll see this is incorrectly defined here:
src/unix/notbsd/linux/other/mod.rs

(the bug is that c_int should be c_uint)

**Comment by jimblandy** [comment]
From the pull request:

> It turns out that eventfd's first argument is `unsigned` on Fedora (glibc), but `int` on Ubuntu (eglibc). Note the delightful contrast between Ubuntu's [code][1] and Ubuntu's [man pages][2]. (The CI logs tell me Trusty is the Ubuntu that Travis is using.)

[1]: http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/trusty/eglibc/trusty/view/head:/sysdeps/unix/sysv/linux/sys/eventfd.h
[2]: http://manpages.ubuntu.com/manpages/trusty/en/man2/eventfd.2.html

**Comment by MarkSwanson** [comment]
Oh my!
How delightful indeed! :-)
