### ISSUE TITLE
c_int instead of c_uint for CLONE_*

### ISSUE THREAD

**Issue by MarkSwanson** [rust-lang-nursery/libc#124]
These are the correct definitions:

pub const CLONE_NEWUTS: ::c_int = 0x04000000;
pub const CLONE_NEWIPC: ::c_int = 0x08000000;
pub const CLONE_NEWUSER: ::c_int = 0x10000000;
pub const CLONE_NEWPID: ::c_int = 0x20000000;
pub const CLONE_NEWNET: ::c_int = 0x40000000;
pub const CLONE_IO: ::c_int = 0x80000000;

These are #define in vi /usr/include/linux/sched.h

They must be c_int because:
- int unshare(int flags);
- int clone(int (*fn)(void *), void *child_stack, int flags, ...

**Comment by alexcrichton** [comment]
Ah probably a mistake on my part, feel free to submit a PR!

**Comment by alexcrichton** [comment]
I believe this was fixed.
