### ISSUE TITLE
Include build instructions

### ISSUE THREAD

**Issue by agrover** [rust-lang-nursery/libc#13]
It doesn't appear to be as simple as "git clone;cargo build" because there's some git subtree stuff needed to pull in from the main rust git? A little hint on this would be great :smile:

**Comment by agrover** [comment]
The only thing I could get working was removing "rust" directory and then running "git subtree add --prefix rust ../rust HEAD", the subtree docs don't really explain how to update into an existing dir...

**Comment by steveklabnik** [comment]
You should `git clone --recursive` instead of a regular `git clone`, so
that it also grabs the submodules.

**Comment by alexcrichton** [comment]
This is now no longer a problem as there are no submodules!
