### ISSUE TITLE
include printf

### ISSUE THREAD

**Issue by durka** [rust-lang-nursery/libc#19]
Is there a reason that `printf` is not exposed in the crate? It can be used [anyway](http://is.gd/LmAlc6) at least on some platforms.

**Comment by alexcrichton** [comment]
Nah there's no particular reason why it isn't bound just yet, but you may be interested in [this RFC](https://github.com/rust-lang/rfcs/pull/1291) which should help ease the expansion of this library!

**Comment by bluss** [comment]
Is libc open to have printf defined now?

**Comment by alexcrichton** [comment]
Certainly!
