### ISSUE TITLE
in6_addr has private fields

### ISSUE THREAD

**Issue by dimbleby** [rust-lang-nursery/libc#41]
The private [`__align`](https://github.com/rust-lang-nursery/libc/blob/3bb2fef25e4716b1e227baba0ba4c5a379a9b795/src/unix/mod.rs#L64) field makes it hard to construct an `in6_addr`.

**Comment by alexcrichton** [comment]
Yeah for now I'd create instances with `mem::uninitialized` or `mem::zeroed` (as you would in C) and then set the fields manually. Unfortunately without a way to specify a custom alignment I don't know of a way around this :(

The good news though is that if we gain the ability to do so the code will be backwards compatible for when the private field is removed!
