### ISSUE TITLE
MAP_STACK is not defined for Open BSD, OS X (android?)

### ISSUE THREAD

**Issue by BurntSushi** [rust-lang-nursery/libc#43]
This was available in `libc` `0.1`, but it looks like it got lost in the move to `0.2`. It looks like it's defined for some other platforms currently though: https://github.com/rust-lang-nursery/libc/search?utf8=%E2%9C%93&q=MAP_STACK

cc @danburkert

**Comment by alexcrichton** [comment]
It looks like this isn't defined on OSX, [forgotten from android](https://github.com/rust-lang-nursery/libc/pull/44), and this also appears to be missing from OpenBSD, so closing in favor of #44.

There may have been other mistakes though where constants were forgotten in the transition, though, and please let me know if you find any!
