### ISSUE TITLE
__align private field in in6_addr

### ISSUE THREAD

**Issue by totakura** [rust-lang-nursery/libc#55]
Hi, is there any reason why __align is declared in in6_addr?  As of now it is preventing in6_addr struct to be created.

**Comment by alexcrichton** [comment]
Ah yeah this is unfortunately because we don't support unions in a great way right now, I'd recommend creating instances via `mem::zeroed` or `mem::uninitialized` and then initializing each member individually (as you would in C). Eventually I hope to remove these fields though!
