### ISSUE TITLE
Impossible to construct an in6_addr

### ISSUE THREAD

**Issue by mrmonday** [rust-lang-nursery/libc#58]
The new definition of `in6_addr`:

```rust
pub struct in6_addr {
    pub s6_addr: [u8; 16],
    __align: [u32; 0],
}
```
Link: https://github.com/rust-lang-nursery/libc/blob/e7ff66ba3df6eb0d10953245a2a6fd2ecf082ccd/src/unix/mod.rs#L62

Means that it is now impossible to construct a value of type `in6_addr` from Rust, outside of the libc crate, since the __align field is private. I've had to fix [libpnet](https://github.com/libpnet/libpnet) to an old version of libc to work around this.

**Comment by alexcrichton** [comment]
Thanks for the report! This has also been reported [here](https://github.com/rust-lang-nursery/libc/issues/55) and [here](https://github.com/rust-lang-nursery/libc/issues/41), and unfortunately this is just a place where Rust doesn't handle FFI unions very well right now. The underlying type is a union which gains it higher alignment but the exposed fields right now don't give us that alignment. When we have custom alignment we may be able to get around this via other means, but for now you can construct this like you would in C:

```rust
let mut foo: libc::in6_addr = mem::uninitialized();
// initialize foo.s6_addr
return foo
```

Which is to say it's not necessarily "impossible", just not very idiomatic!

**Comment by mrmonday** [comment]
Thanks you. Sorry for the noise, I didn't find those issues when I searched for some reason.

**Comment by s3bk** [comment]
It should be possible to replace __align with `#[repr(C, align(32))]` now. Or am I wrong here?
