### ISSUE TITLE
Add BSD CI

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/libc#75]
I'd love to add CI for BSD variants like FreeBSD, Bitrig, OpenBSD, DragonFlyBSD, etc,  but currently I don't know how to run binaries targeting these platforms.

Here's a tracking issue trying to figure this out!

cc @dhuseby, @semarie

**Comment by alexcrichton** [comment]
cc @mneumann

**Comment by dhuseby** [comment]
what is Cl?

**Comment by alexcrichton** [comment]
Ah sorry, CI == continuous integration == travis probably

**Comment by semarie** [comment]
@alexcrichton if you want running binaries, I think it won't be possible: according to https://github.com/travis-ci/travis-ci/issues/1818 there is no freebsd support (so others BSD aren't be supported too).

But if you want to build binaries (and it will be a good test) it could be possible with the `libcore-xxxx.rlib` from the target (if I recall correctly, it is the sole dependency libc has), and building with --target. but I dunno how to keep updated `libcore-xxxx.rlib` in the build env.

**Comment by alexcrichton** [comment]
Yeah unfortunately this isn't easy to do, it may not be possible with travis. One option would be to use QEMU perhaps, but I'm not sure of other ways.

**Comment by alexcrichton** [comment]
This has been done! We've got a template at least for future BSDs
