### ISSUE TITLE
netbsd doesn't declare pthread_setname_np, which libstd uses

### ISSUE THREAD

**Issue by skade** [rust-lang-nursery/libc#77]
Cross-Compiling current rustc libstd to netbsd fails with this (actual target being `x86_64-rumprun-netbsd`:

```
src/libstd/sys/unix/thread.rs:124:13: 124:37 error: unresolved name `libc::pthread_setname_np` [E0425]
src/libstd/sys/unix/thread.rs:124             libc::pthread_setname_np(libc::pthread_self(), cname.as_ptr(),
```

netbsd documents the function, so adding it should work.

**Comment by alexcrichton** [comment]
Ah this may have just been forgotten in the reshuffling of the library, should be fine to add back though!

**Comment by skade** [comment]
I think it was forgotten to add to libc when it was removed here. :D

https://github.com/rust-lang/rust/blob/318cd843d1103579291a9f6c9eab8aacce7e9f82/src/libstd/sys/unix/thread.rs#L130-L134
