### ISSUE TITLE
Adding in a lot of *nix ioctl constants

### ISSUE THREAD

**Issue by derekdreery** [rust-lang-nursery/libc#97]
I've started working on including all the constants in the ioctl.h and related headers (see https://github.com/derekdreery/libc), I've spent quite a long time on it, so before I do any more I'd like to make sure I'm doing something useful. Currently the library is not building because I'm using size_of in a constant context (shouldn't the size of all types be available at compile-time?). I need to calculate the size of the structs by hand and include that in.

There are some issues (all request codes should be c_ulong looking at the sys/ioctl.h definition of ioctl). I'll work on fixing these if the code will be useful.

Thanks

**Comment by alexcrichton** [comment]
Awesome! These definitely belong here :)

Currently this library compiles on Rust 1.0 and I'd like to keep that requirement if possible, so it may make the definitions a little wordy in terms of what's needed at compile-time but there should in theory be all the necessary modules in place to organize this.

Let me know if you need any help!

**Comment by derekdreery** [comment]
OK that's fine it might be worth someone else calculating the sizes as well as me - since that kinda defeats the whole memory safety thing if I get it wrong :P

**Comment by derekdreery** [comment]
I'll have a tidying up pass before I make a pull request

**Comment by derekdreery** [comment]
Ok so here's my justification for my size_of s

Input: 

```rust
pub type c_uchar = u8;
pub type c_ushort = u16;
pub type c_uint = u32;
pub type c_int = i32;

pub type cc_t = c_uchar;
pub type speed_t = c_uint;
pub type tcflag_t = c_uint;

pub struct termio {
    /// input mode flags
    pub c_iflag: ::c_ushort,
    /// output mode flags
    pub c_oflag: ::c_ushort,
    /// control mode flags
    pub c_cflag: ::c_ushort,
    /// local mode flags
    pub c_lflag: ::c_ushort,
    /// line discipline
    pub c_line: ::c_uchar,
    /// control characters
    pub c_cc: [::c_uchar; 8] // 8 = number of control characters
}

pub struct termios {
    /// input mode flags
    pub c_iflag: tcflag_t,
    /// output mode flags
    pub c_oflag: tcflag_t,
    /// control mode flags
    pub c_cflag: tcflag_t,
    /// local mode flags
    pub c_lflag: tcflag_t,
    /// line discipline
    pub c_line: cc_t,
    /// control characters
    pub c_cc: [cc_t; 19], // 19 = number of control characters
}

pub struct termios2 {
    /// input mode flags
    pub c_iflag: tcflag_t,
    /// output mode flags
    pub c_oflag: tcflag_t,
    /// control mode flags
    pub c_cflag: tcflag_t,
    /// local mode flags
    pub c_lflag: tcflag_t,
    /// line discipline
    pub c_line: cc_t,
    /// control characters
    pub c_cc: [cc_t; 19], // 19 = number of control characters
    /// input speed
    pub c_ispeed: speed_t,
    /// output speed
    pub c_ospeed: speed_t
}

fn main() {
    println!("Size of c_uint = {}", ::std::mem::size_of::<c_uint>());
    println!("Size of c_int = {}", ::std::mem::size_of::<c_int>());
    println!("Size of termio = {}", ::std::mem::size_of::<termio>());
    println!("Size of termios = {}", ::std::mem::size_of::<termios>());
    println!("Size of termios2 = {}", ::std::mem::size_of::<termios2>());
}
```

Output:
```
Size of c_uint = 4
Size of c_int = 4
Size of termio = 18
Size of termios = 36
Size of termios2 = 44
```

**Comment by alexcrichton** [comment]
Ok, cool, I'm gonna close this in favor of the [PR you've now opened](https://github.com/rust-lang-nursery/libc/pull/99), thanks!
